language: java
jdk:
  - oraclejdk7

install: /bin/true

script: ./gradlew build

deploy:
  - provider: script
    script: ./gradlew bintrayUpload -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_KEY} -PdryRun=false
    skip_cleanup: true
    on:
      tags: true
